config/routes.rb
Rails.application.routes.draw do
  root to: "devices#index"
  resources :sensors
  resources :devices
  namespace :api do
    namespace :v1 do
      resources :devices
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord

  # association
  has_many :sensors, dependent: :destroy
  accepts_nested_attributes_for :sensors, allow_destroy: true

  # validation
  validates :name, presence: true
  validates :category, presence: true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  # association
  belongs_to :device
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::Base
  before_action :set_default_response_format

  private

  def set_default_response_format
  	request.format = :json
  end
end

app/controllers/api/v1/devices_controller.rb
module Api
  module V1
    class DevicesController < ApiController

      include Broadcastable
      before_action :set_device, only: [:show, :update, :destroy]
      after_action :broadcast_sensor_state, only: :update


      # GET /devices.json
      def index
        @devices = Device.all
      end
      
      # GET /devices/1.json
      def show
      end

      # POST /devices.json
      def create
        @device = Device.new(device_params)

        respond_to do |format|
          if @device.save
            format.json { render :show, status: :created, location: @device }
          else
            format.json { render json: @device.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /devices/1.json
      def destroy
        @device.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      end

      # PATCH/PUT /devices/1.json
      def update
        respond_to do |format|
          if @device.update(device_params)
            format.html { redirect_to @device, notice: 'Device was successfully updated.' }
            format.json { render :show, status: :ok, location: @device }
          else
            format.html { render :edit }
            format.json { render json: @device.errors, status: :unprocessable_entity }
          end
        end
      end

      private

      def set_device
        @device = Device.find(params[:id])
      end

      def device_params
        params.require(:device).permit(:name, :category, sensors_attributes: [  :id, :name, :value ] )
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/broadcastable.rb
module Broadcastable
  extend ActiveSupport::Concern
  
  def broadcast_sensor_state
    ActionCable.server.broadcast 'sensor_notifications_channel',
        message: render_message(@device.sensors)
  end

  private

  def render_message(sensors)
    ApplicationController.render(partial: 'sensors/sensors_table',
                                 locals: { sensors: sensors })
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :category)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :value, :device_id)
    end
end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/api/v1/devices_helper.rb
module Api::V1::DevicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.number_field :category
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %thead
    %tr
      %th Name
      %th Category
      %th
      %th
      %th

  %tbody
    - @devices.each do |device|
      %tr
        %td= device.name
        %td= device.category
        %td= link_to 'Show', device
        %td= link_to 'Edit', edit_device_path(device)
        %td= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @device.name
%p
  %b Category:
  = @device.category
%p
  %b Sensors:
  #device_sensors
    = render 'sensors/sensors_table', sensors: @device.sensors


= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sensors/_form.html.haml
= form_for @sensor do |f|
  - if @sensor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sensor.errors.count, "error")} prohibited this sensor from being saved:"
      %ul
        - @sensor.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :device_id
    = f.number_field :device_id
  .actions
    = f.submit 'Save'

app/views/sensors/_sensor_row.html.haml
%tr
  %td= sensor.name
  %td= sensor.value
  %td= link_to 'Show', sensor
  %td= link_to 'Edit', edit_sensor_path(sensor)
  %td= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' }

app/views/sensors/_sensors_table.html.haml
%table
  %thead
    %tr
      %th Name
      %th Value
      %th
      %th
      %th

  %tbody
    - sensors.each do |sensor|
      = render 'sensors/sensor_row', sensor: sensor

app/views/sensors/edit.html.haml
%h1 Editing sensor

= render 'form'

= link_to 'Show', @sensor
\|
= link_to 'Back', sensors_path

app/views/sensors/index.html.haml
%h1 Listing sensors
= render 'sensors_table', sensors: @sensors

%br

= link_to 'New Sensor', new_sensor_path

app/views/sensors/new.html.haml
%h1 New sensor

= render 'form'

= link_to 'Back', sensors_path

app/views/sensors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @sensor.name
%p
  %b Value:
  = @sensor.value

= link_to 'Edit', edit_sensor_path(@sensor)
\|
= link_to 'Back', sensors_path